const products = [
    { name: "Arroz", type: "Alimentos", brand: "Camil", price: 25.00 },
    { name: "Feijão", type: "Alimentos", brand: "Camil", price: 10.00 },
    { name: "Macarrão", type: "Alimentos", brand: "Barilla", price: 15.00 },
    { name: "Leite", type: "Bebidas", brand: "Itambé", price: 6.00 },
    { name: "Refrigerante", type: "Bebidas", brand: "Coca-Cola", price: 8.00 },
    { name: "Cerveja", type: "Bebidas", brand: "Heineken", price: 7.00 },
    { name: "Relógio", type: "Acessórios", brand: "Casio", price: 350.00 },
    { name: "Pulseira", type: "Acessórios", brand: "Vivara", price: 150.00 },
    { name: "Óculos de Sol", type: "Acessórios", brand: "Ray-Ban", price: 600.00 },
    { name: "Jaqueta", type: "Roupas", brand: "Adidas", price: 450.00 },
    { name: "Calça Jeans", type: "Roupas", brand: "Levi's", price: 200.00 },
    { name: "Camisa Polo", type: "Roupas", brand: "Lacoste", price: 300.00 },
    { name: "Biscoito", type: "Alimentos", brand: "Bauducco", price: 5.00 },
    { name: "Suco", type: "Bebidas", brand: "Del Valle", price: 4.50 },
    { name: "Café", type: "Alimentos", brand: "Melitta", price: 18.00 },
    { name: "Vinho", type: "Bebidas", brand: "Casillero del Diablo", price: 60.00 },
    { name: "Chaveiro", type: "Acessórios", brand: "Hering", price: 20.00 },
    { name: "Boné", type: "Acessórios", brand: "New Era", price: 90.00 },
    { name: "Blusa de Moletom", type: "Roupas", brand: "Gap", price: 220.00 },
    { name: "Sapato", type: "Roupas", brand: "Lacoste", price: 400.00 },
    { name: "Suéter", type: "Roupas", brand: "Tommy Hilfiger", price: 280.00 },
    { name: "Queijo", type: "Alimentos", brand: "Polenghi", price: 25.00 },
    { name: "Pizza Congelada", type: "Alimentos", brand: "Sadia", price: 18.00 },
    { name: "Água", type: "Bebidas", brand: "Crystal", price: 2.50 },
    { name: "Whisky", type: "Bebidas", brand: "Jack Daniel's", price: 130.00 },
    { name: "Mochila", type: "Acessórios", brand: "Jansport", price: 200.00 },
    { name: "Carteira", type: "Acessórios", brand: "Tommy Hilfiger", price: 120.00 },
    { name: "Chinelo", type: "Roupas", brand: "Havaianas", price: 35.00 },
    { name: "Camisa Social", type: "Roupas", brand: "Zara", price: 150.00 },
    { name: "Calça de Moletom", type: "Roupas", brand: "Nike", price: 250.00 },
    { name: "Maçã", type: "Alimentos", brand: "Nature", price: 8.00 },
    { name: "Pão", type: "Alimentos", brand: "Pullman", price: 12.00 },
    { name: "Cerveja Artesanal", type: "Bebidas", brand: "Colorado", price: 15.00 },
    { name: "Energético", type: "Bebidas", brand: "Red Bull", price: 10.00 },
    { name: "Colar", type: "Acessórios", brand: "Pandora", price: 400.00 },
    { name: "Brincos", type: "Acessórios", brand: "Vivara", price: 200.00 },
    { name: "Vestido", type: "Roupas", brand: "Forever 21", price: 180.00 },
    { name: "Blusa", type: "Roupas", brand: "C&A", price: 60.00 },
    { name: "Casaco", type: "Roupas", brand: "Renner", price: 250.00 },
    { name: "Queijo Parmesão", type: "Alimentos", brand: "Faixa Azul", price: 45.00 },
    { name: "Presunto", type: "Alimentos", brand: "Sadia", price: 25.00 },
    { name: "Vodka", type: "Bebidas", brand: "Absolut", price: 80.00 },
    { name: "Chá Gelado", type: "Bebidas", brand: "Leão", price: 5.00 },
    { name: "Gorro", type: "Acessórios", brand: "Adidas", price: 70.00 },
    { name: "Cachecol", type: "Acessórios", brand: "Burberry", price: 500.00 },
    { name: "Gravata", type: "Acessórios", brand: "Hermès", price: 800.00 }
  ];

  export default products
  